### PR TITLE
add zuri training mentors search with filter

### PR DESCRIPTION
**Pull request by CeoFred**

### CODE REVIEW

**Comment by kenny-67** [comment]
I already did this na

**Comment by kenny-67** [comment]
Check the merged pr you would see it

**Comment by CeoFred** [comment]
You have 4 different controllers to manage just this one task, I've got not more than 15 lines doing same thing and even more, do check it out and if possible revert.

**Comment by kenny-67** [comment]
i splitted the search and filter functionality to two different endpoints, it's better that way

**Comment by CeoFred** [comment]
the search always has a filter, you did not see that on the design??

**Pull request merged**
